CREATE TABLE DOG_INFO (
	DOG_ID VARCHAR2(50)	NOT NULL,
	DOG_IMG	VARCHAR2(4000)	NULL,
	DOG_NAME VARCHAR2(100)	NOT NULL,
	DOG_KIND VARCHAR2(100)	NOT NULL,
	DOG_SIZE CHAR(4)	NOT NULL,
	DOG_GENDER CHAR(4)	NOT NULL,
	DOG_NEUTERED CHAR(1)	DEFAULT 'N' NOT NULL,
	DOG_VACCINE	VARCHAR2(1000)	NOT NULL,
	MEMBER_CODE	VARCHAR2(20)	NOT NULL,
    CONSTRAINT 
);