CREATE TABLE DOG_INFO (
	D_ID VARCHAR2(50),
	D_IMG	VARCHAR2(4000),
    D_NUM NUMBER,
	D_NAME VARCHAR2(100) NOT NULL,
	D_KIND VARCHAR2(100) NOT NULL,
	D_SIZE VARCHAR2(10) NOT NULL,
	D_GENDER VARCHAR(10) NOT NULL,
	NEUTERED CHAR(1) NOT NULL,
	VACCINE	VARCHAR2(1000) NOT NULL,
	MEM_CODE NUMBER NOT NULL,
    CONSTRAINT DOG_INFO_ID_PK PRIMARY KEY(D_ID),
    CONSTRAINT MEMBER_MEM_CODE_FK FOREIGN KEY (MEM_CODE) REFERENCES MEMBER
);


COMMENT ON COLUMN DOG_INFO.D_ID IS '아이디';
COMMENT ON COLUMN DOG_INFO.D_IMG IS '사진';
COMMENT ON COLUMN DOG_INFO.D_NUM IS '번호';
COMMENT ON COLUMN DOG_INFO.D_NAME IS '이름';
COMMENT ON COLUMN DOG_INFO.D_KIND IS '견종';
COMMENT ON COLUMN DOG_INFO.D_SIZE IS '크기';
COMMENT ON COLUMN DOG_INFO.D_GENDER IS '성별';
COMMENT ON COLUMN DOG_INFO.NEUTERED IS '중성화';
COMMENT ON COLUMN DOG_INFO.VACCINE IS '백신접종';

CREATE SEQUENCE DOG_ID;


DROP TABLE DOG_INFO;

DROP SEQUENCE DOG_ID;

INSERT INTO DOG_INFO (
    D_ID,
    D_IMG,
    D_NUM,
    D_NAME,
    D_KIND,
    D_SIZE,
    D_GENDER,
    NEUTERED,
    VACCINE,
    MEM_CODE
) VALUES(
    'DOG' || DOG_ID.NEXTVAL,
    'NULL',
    1,
    '보리',
    '미니어쳐 핀셔',
    '소형견',
    'F',
    'N',
    '접종안함',
    '1'
);

INSERT INTO DOG_INFO (
    D_ID,
    D_IMG,
    D_NUM,
    D_NAME,
    D_KIND,
    D_SIZE,
    D_GENDER,
    NEUTERED,
    VACCINE,
    MEM_CODE
) VALUES(
    'DOG' || DOG_ID.NEXTVAL,
    'NULL',
    2,
    '수리',
    '닥스훈트',
    '소형견',
    'M',
    'N',
    '신종플루',
    '1'
);

SELECT D_NUM, D_NAME, D_KIND, D_SIZE, D_GENDER, NEUTERED, VACCINE, MEM_CODE
FROM DOG_INFO
WHERE MEM_CODE = 1;

COMMIT;

CREATE TABLE MEMBER (
    MEM_CODE NUMBER,
    MEM_ID VARCHAR2(20) CONSTRAINT MEM_ID_NN NOT NULL,
    MEM_PWD VARCHAR2(20) CONSTRAINT MEM_PWD_NN NOT NULL,
    MEM_NAME VARCHAR2(100) CONSTRAINT MEM_NAME_NN NOT NULL,
    MEM_NICKNAME VARCHAR2(100) CONSTRAINT MEM_NICKNAME_NN NOT NULL,
    MEM_PHONE varchar2(12) CONSTRAINT MEM_PHONE_NN NOT NULL,
    MEM_ADDRESS VARCHAR2(150) CONSTRAINT MEM_ADDRESS_NN NOT NULL,
    MEM_EMAIL VARCHAR2(150) CONSTRAINT MEM_EMAIL_NN NOT NULL,
    MEM_BIRTH DATE CONSTRAINT MEM_BIRTH_NN NOT NULL,
    MEM_SU_DATE DATE  DEFAULT SYSDATE CONSTRAINT MEM_REG_DATE_NN NOT NULL,
    MEM_GENDER VARCHAR2(1) CONSTRAINT MEM_GENDER_NN NOT NULL CONSTRAINT MEM_GENDER_CK CHECK(MEM_GENDER IN ('M','F')),
    MEM_STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT MEM_STATUS_NN NOT NULL CONSTRAINT MEM_STATUS_CK CHECK(MEM_STATUS IN ('Y','N')), 
    CONSTRAINT "MEM_PK" PRIMARY KEY ("MEM_CODE"),
    CONSTRAINT "MEM_ID_UQ" UNIQUE ("MEM_ID"),
    CONSTRAINT "MEM_NICKNAME_UQ" UNIQUE ("MEM_NICKNAME"),
    CONSTRAINT "MEM_EMAIL_UQ" UNIQUE ("MEM_EMAIL")
);

COMMENT ON COLUMN MEMBER.MEM_CODE IS '회원코드'; 
COMMENT ON COLUMN MEMBER.MEM_ID IS '아이디'; 
COMMENT ON COLUMN MEMBER.MEM_PWD IS '비밀번호'; 
COMMENT ON COLUMN MEMBER.MEM_NAME IS '이름'; 
COMMENT ON COLUMN MEMBER.MEM_NICKNAME IS '닉네임'; 
COMMENT ON COLUMN MEMBER.MEM_PHONE IS '핸드폰번호'; 
COMMENT ON COLUMN MEMBER.MEM_BIRTH IS '생년월일'; 
COMMENT ON COLUMN MEMBER.MEM_ADDRESS IS '주소'; 
COMMENT ON COLUMN MEMBER.MEM_EMAIL IS '이메일'; 
COMMENT ON COLUMN MEMBER.MEM_SU_DATE IS '가입일'; 
COMMENT ON COLUMN MEMBER.MEM_GENDER IS '성별'; 
COMMENT ON COLUMN MEMBER.MEM_STATUS IS '회원상태';

CREATE SEQUENCE MEM_CODE_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1 
MAXVALUE 99999999999999
NOCYCLE
NOCACHE;

DROP SEQUENCE MEM_CODE_SEQ;

DROP TABLE MEMBER;

UPDATE MEMBER SET MEM_NICKNAME='이나브로', MEM_PHONE='01012345678', MEM_ADDRESS='서울 송파구' WHERE MEM_CODE=2;

ROLLBACK;

SELECT * FROM DOG_INFO WHERE MEM_CODE=2;

CREATE TABLE BOARD (
   BOARD_NO   NUMBER   NOT NULL,
   BOARD_CODE   VARCHAR2(40) NOT NULL,
   BOARD_NUMBER   NUMBER   NOT NULL,
   BOARD_TITLE   VARCHAR2(40) NOT NULL,
   MEMBER_CODE   NUMBER   NOT NULL,
   BOARD_CONTENT   VARCHAR2(2000) NOT NULL,
   SUBJECT_ID   VARCHAR2(20) ,
   CREATE_DATE   DATE DEFAULT SYSDATE NOT NULL,
   MODIFY_DATE DATE DEFAULT SYSDATE,
   VIEWS   NUMBER DEFAULT 0  NOT NULL,
   BOARD_STATUS CHAR(1) DEFAULT 'Y' NOT NULL,
   CONSTRAINT BOARD_BOARD_STATUS_CK CHECK(BOARD_STATUS IN('Y','N'))
);

DROP TABLE BOARD;

CREATE SEQUENCE SEQ_BOARD_NO;

CREATE SEQUENCE SEQ_NOTICE_NO;
CREATE SEQUENCE SEQ_QNA_NO;
CREATE SEQUENCE SEQ_INFO_NO;
CREATE SEQUENCE SEQ_INTRODUCE_NO;
CREATE SEQUENCE SEQ_REVIEW_NO;
CREATE SEQUENCE SEQ_REPORT_NO;

BEGIN
    FOR N IN 1..10
    LOOP INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'B1', SEQ_INTRODUCE_NO.NEXTVAL,
'우리 아이는요~'|| SEQ_INTRODUCE_NO.CURRVAL, 1, '예뻐요'|| SEQ_INTRODUCE_NO.CURRVAL, NULL, SYSDATE, SYSDATE, DEFAULT, 'Y');
END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..10
    LOOP INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'B2', SEQ_REVIEW_NO.NEXTVAL,
'리뷰작성완료~'|| SEQ_REVIEW_NO.CURRVAL, 1, '다음에도 만나자 이슬모니~'|| SEQ_REVIEW_NO.CURRVAL, NULL, SYSDATE, SYSDATE, DEFAULT, 'Y');
END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..10
    LOOP INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'B3', SEQ_INFO_NO.NEXTVAL,
'동물병원 추천'|| SEQ_INFO_NO.CURRVAL, 1, '역삼역 동물병원 추천드림 믿고가보셈'|| SEQ_INFO_NO.CURRVAL, NULL, SYSDATE, SYSDATE, DEFAULT, 'Y');
END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..10
    LOOP INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'B4', SEQ_QNA_NO.NEXTVAL,
'강아지 간식문의'|| SEQ_QNA_NO.CURRVAL, 1, '요즘은 어떤 간식 주나요?'|| SEQ_QNA_NO.CURRVAL, NULL, SYSDATE, SYSDATE, DEFAULT, 'Y');
END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..10
    LOOP INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'B5', SEQ_NOTICE_NO.NEXTVAL,
'공지사항'|| SEQ_NOTICE_NO.CURRVAL, 1, '이번 시즌 강아지장터 공지'|| SEQ_NOTICE_NO.CURRVAL, NULL, SYSDATE, SYSDATE, DEFAULT,'Y');
END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..10
    LOOP INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, 'B6', SEQ_REPORT_NO.NEXTVAL,
'신고합니다!'|| SEQ_REPORT_NO.CURRVAL, 1, '왜 뒤처리 안하시나요.;'|| SEQ_REPORT_NO.CURRVAL, NULL, SYSDATE, SYSDATE, DEFAULT, 'Y');
END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

INSERT INTO BOARD_CODE VALUES('B1', '펫 다이어리', 'M');
INSERT INTO BOARD_CODE VALUES('B2', '펫미팅 후기', 'M');
INSERT INTO BOARD_CODE VALUES('B3', '정보공유', 'M');
INSERT INTO BOARD_CODE VALUES('B4', '문의/건의', 'M');
INSERT INTO BOARD_CODE VALUES('B5', '공지사항', 'A');
INSERT INTO BOARD_CODE VALUES('B6', '신고하기', 'M');