-- 총 게시글 조회 개수
SELECT COUNT(*) FROM WALKBOARD WHERE WB_STATUS='Y';

-- 목록 조회(페이징)
SELECT RNUM, WB_NO, WB_TITLE, M_NICKNAME, CREATE_DATE, WB_VIEWS, WB_STATUS, ORIGINAL_FILENAME
FROM (
        SELECT ROWNUM AS RNUM,
        WB_NO,
        WB_TITLE,
        M_NICKNAME,
        CREATE_DATE,
        WB_VIEWS,
        WB_STATUS,
        ORIGINAL_FILENAME
        FROM (
        SELECT  WB.WB_NO,
                WB.WB_TITLE,
                M.M_NICKNAME,
                WB.CREATE_DATE,
                WB.WB_VIEWS,
                WB.WB_STATUS,
                WB.ORIGINAL_FILENAME
        FROM WALKBOARD WB JOIN MEMBER M ON(WB.M_CODE = M.M_CODE) 
        WHERE WB.WB_STATUS = 'Y' ORDER BY WB.WB_NO DESC
    )
)
WHERE RNUM BETWEEN ? and ?;

-- 상세 조회 (마이페이지 강아지 정보 보임)
SELECT  WB.WB_NO, WB.WB_TITLE, M.M_NICKNAME, WB.WB_VIEWS, WB.WB_CONTENT, WB.CREATE_DATE, WB.MODIFY_DATE, WB.ORIGINAL_FILENAME, WB.RENAMED_FILENAME
FROM WALKBOARD WB
JOIN MEMBER M ON(WB.M_CODE = M.M_CODE)
WHERE WB.WB_STATUS = 'Y' AND WB.WB_NO=?;

-- 조회수 증가
UPDATE WALKBOARD SET WB_VIEWS=? WHERE WB_NO=?;

-- 댓글 조회
SELECT M.M_CODE, R.WR_NO, R.WB_NO, R.WR_CONTENT, M.M_NICKNAME, R.CREATE_DATE, R.MODIFY_DATE
FROM WALKREPLY R
JOIN MEMBER M ON(R.M_CODE = M.M_CODE)
WHERE R.WR_STATUS='Y' AND WR_NO=?
ORDER BY R.WR_NO DESC;

-- 댓글 등록
INSERT INTO WALKREPLY VALUES (WR_NO_SEQ.NEXTVAL, ?, ?, ?, SYSDATE, SYSDATE, DEFAULT);

-- 게시글 등록
INSERT INTO WALKBOARD VALUES (WB_NO_SEQ.NEXTVAL, ?, ?, ?, ?, DEFAULT, DEFAULT, 0, DEFAULT, DEFAULT, DEFAULT);

-- 게시글 삭제
UPDATE WALKBOARD SET WB_STATUS=? WHERE WB_NO=?;

-- 게시글 수정
UPDATE WALKBOARD SET WB_TITLE=?, WB_CONTENT=?, ORIGINAL_FILENAME=DEFAULT, RENAMED_FILENAME=DEFAULT, MODIFY_DATE=SYSDATE WHERE WB_NO=?;

-- 댓글 삭제
UPDATE WALKREPLY SET WR_STATUS=? WHERE WR_NO=?;

COMMIT;