-- MEMBER
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER1', '1234', '사용자1', '유저1', 01011111111, '서울특별시', 'AAA@AAA.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER2', '1234', '사용자2', '유저2', 01022222222, '서울특별시', 'BBB@BBB.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER3', '1234', '사용자3', '유저3', 01033333333, '서울특별시', 'CCC@CCC.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER4', '1234', '사용자4', '유저4', 01044444444, '서울특별시', 'DDD@DDD.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER5', '1234', '사용자5', '유저5', 01055555555, '서울특별시', 'EEE@EEE.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER6', '1234', '사용자6', '유저6', 01066666666, '서울특별시', 'FFF@FFF.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER7', '1234', '사용자7', '유저7', 01077777777, '서울특별시', 'GGG@GGG.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER8', '1234', '사용자8', '유저8', 01088888888, '서울특별시', 'HHH@HHH.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER9', '1234', '사용자9', '유저9', 01099999999, '서울특별시', 'III@III.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER10', '1234', '사용자10', '유저10', 01000000000, '서울특별시', 'JJJ@JJJ.COM', SYSDATE, SYSDATE, 'F', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER11', '1234', '사용자11', '유저11', 01012341234, '서울특별시', 'KKK@KKK.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER12', '1234', '사용자12', '유저12', 01056785678, '서울특별시', 'LLL@LLL.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER13', '1234', '사용자13', '유저13', 01091239123, '서울특별시', 'MMM@MMM.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER14', '1234', '사용자14', '유저14', 01045674567, '서울특별시', 'OOO@OOO.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER15', '1234', '사용자15', '유저15', 01089018901, '서울특별시', 'PPP@PPP.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER16', '1234', '사용자16', '유저16', 01023452345, '서울특별시', 'QQQ@QQQ.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER17', '1234', '사용자17', '유저17', 01067896789, '서울특별시', 'RRR@RRR.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER18', '1234', '사용자18', '유저18', 01001230123, '서울특별시', 'SSS@SSS.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER19', '1234', '사용자19', '유저19', 01045674567, '서울특별시', 'TTT@TTT.COM', SYSDATE, SYSDATE, 'M', 'Y');
INSERT INTO MEMBER VALUES (MEM_CODE_SEQ.NEXTVAL, 'USER20', '1234', '사용자20', '유저20', 01089018901, '서울특별시', 'UUU@UUU.COM', SYSDATE, SYSDATE, 'M', 'Y');

-- MYPAGE
INSERT INTO MYPAGE VALUES (1, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (21, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (22, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (23, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (24, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (25, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (26, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (27, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (28, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (29, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (30, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (31, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (32, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (33, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (34, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (35, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (36, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (37, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (38, 'N', '안녕하세요');
INSERT INTO MYPAGE VALUES (39, 'N', '안녕하세요');

-- DOG_INFO
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리1', '미니핀', '중형견', '암컷', 'Y', 'Y', 1);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리2', '미니핀', '중형견', '암컷', 'Y', 'Y', 21);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리3', '미니핀', '중형견', '암컷', 'Y', 'Y', 22);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리4', '미니핀', '중형견', '암컷', 'Y', 'Y', 23);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리5', '미니핀', '중형견', '암컷', 'Y', 'Y', 24);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리6', '미니핀', '중형견', '암컷', 'Y', 'Y', 25);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리7', '미니핀', '중형견', '암컷', 'Y', 'Y', 26);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리8', '미니핀', '중형견', '암컷', 'Y', 'Y', 27);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리9', '미니핀', '중형견', '암컷', 'Y', 'Y', 28);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리10', '미니핀', '중형견', '암컷', 'Y', 'Y', 29);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리11', '미니핀', '중형견', '암컷', 'Y', 'Y', 30);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리12', '미니핀', '중형견', '암컷', 'Y', 'Y', 31);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리13', '미니핀', '중형견', '암컷', 'Y', 'Y', 32);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리14', '미니핀', '중형견', '암컷', 'Y', 'Y', 33);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리15', '미니핀', '중형견', '암컷', 'Y', 'Y', 34);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리16', '미니핀', '중형견', '암컷', 'Y', 'Y', 35);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리17', '미니핀', '중형견', '암컷', 'Y', 'Y', 36);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리18', '미니핀', '중형견', '암컷', 'Y', 'Y', 37);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리19', '미니핀', '중형견', '암컷', 'Y', 'Y', 38);
INSERT INTO DOG_INFO VALUES (DOG_ID_SEQ.NEXTVAL, NULL, '보리20', '미니핀', '중형견', '암컷', 'Y', 'Y', 39);

-- WALK_BOARD
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 1, 1, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 21, 2, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 22, 3, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 23, 4, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 24, 5, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 25, 6, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 26, 7, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 27, 8, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 28, 9, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 29, 10, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 30, 11, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 31, 12, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 32, 13, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 33, 14, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 34, 15, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 35, 16, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 36, 17, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 37, 18, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 38, 19, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 39, 20, '산책 친구 구합니다', '산책 친구 구합니다', SYSDATE, SYSDATE, 0, 'Y');
INSERT INTO WALK_BOARD VALUES (WB_NO_SEQ.NEXTVAL, 39, 20, '산책 친구 구합니다', '산책 친구 구합니다', DEFAULT, DEFAULT, 0, DEFAULT);

-- WALK_COMMENT
INSERT INTO "WALK_COMMENT" VALUES (WC_NO_SEQ.NEXTVAL, 1, '유저1', '저랑 산책 하실래요?', SYSDATE, SYSDATE, 'Y');
INSERT INTO "WALK_COMMENT" VALUES (WC_NO_SEQ.NEXTVAL, 2, '유저2', '저랑 산책 하실래요?', SYSDATE, SYSDATE, 'Y');
INSERT INTO "WALK_COMMENT" VALUES (WC_NO_SEQ.NEXTVAL, 3, '유저3', '저랑 산책 하실래요?', SYSDATE, SYSDATE, 'Y');
INSERT INTO "WALK_COMMENT" VALUES (WC_NO_SEQ.NEXTVAL, 4, '유저4', '저랑 산책 하실래요?', SYSDATE, SYSDATE, 'Y');
INSERT INTO "WALK_COMMENT" VALUES (WC_NO_SEQ.NEXTVAL, 5, '유저5', '저랑 산책 하실래요?', SYSDATE, SYSDATE, 'Y');

COMMIT;